### ISSUE TITLE
配置的source_root没有被使用，而且ignore的配置是基于project_root的

### ISSUE THREAD

**Issue by MrLiu199** [luxel/ramile#2]
我这里的修复方法如下：
![bug 01](https://user-images.githubusercontent.com/34264250/47267057-07949980-d571-11e8-9b20-d011ab521aed.png)

添加上配置source_root的这行
self.__set_config_root(config_data)

将project_root修改为source_root
这样就可以使ignore是基于project_root+source_root

**Comment by luxel** [comment]
谢谢反馈，已经修复
